import ArticlePage from "@/components/ArticlePage";
import { articleMetadata } from "@/lib/articleMeta";

export const metadata = articleMetadata({
  slug: "politicti-vezni",
  title: "Vězení a bdělost",
  description:
    "Václav Havel ve své pantomimě, jejíž libreto napsal ve vězení, zaujímá k situaci uvěznění emancipující odstup. Píše Tomáš Glanc.",
  image: "/1766237746-perpetuum-6.jpg",
});

const ODSTAVCE = [
  "Psaní ve vězení je historicky pro umělce a intelektuála něčím téměř paradigmatickým. Tedy za předpokladu, že podmínky věznění samotný akt psaní umožňují a podaří se vyřešit předání nebo vynesení textu „ven“. Vzniká tak svérázný kánon „vězeňské literatury“, pro který je příznačné stupňování významu díla překážkami a příkořím, které jeho vznik provázejí. I u Havla je součástí významu scénáře pantomimy fakt, že první verzi cenzura zabavila, autor musel do dopisu rozsah radikálně redukovat a podobně.",
  "Typický příklad pro historické dílo, jehož význam je pevně spojen s příběhem jeho vzniku ve vězení, je hra Silvia Pellica, italského politického aktivisty a zastánce jednotné Itálie, člena karbonářského hnutí, kterého v roce 1820 rakouské úřady zatkly a o čtyři roky později odsoudily nejprve k smrti a poté, co byl omilostněn císařem Františkem Josefem I., k dlouholetému vězení – nejdříve je odbýval v Benátkách a potom na Špilberku v Brně. Právě tam měla vzniknout pětiaktová tragédie Leoniero da Dertona (Leoniero z Tortony).",
  "Veršované dílo se vyznačuje extrémním kvalitativním rysem, jenž se v podobných případech mnohokrát zopakoval: Autor se celý text naučil zpaměti, protože v žaláři nedostal psací potřeby. Písemně je zrekonstruoval až po propuštění roku 1830. Podobně bude za stalinismu o více než sto let později – na přelomu 40. a 50. let – zpaměti skládat svoji rozsáhlou autobiografickou veršovanou skladbu Dorožeňka (Cestička) v sovětském GULAGu Alexandr Solženicyn (poéma vyšla až v roce 1999). V časovém rozpětí mezi Pellicem a Solženicynem bylo psaní významných děl ve vězení jevem téměř notoricky známým.",
  "Tak Nikolaj Černyševskij svůj politický román Čto dělať (Co dělat) s kultovním snem Věry Pavlovny o spravedlivé společnosti budoucího věku napsal v petěrburské věznici. Román mimochodem vycházel, tolerovaný carskou cenzurou, v první polovině 60. let 19. století v Rusku časopisecky, zatímco jeho autor byl nadále vězněn. Vězněm svědomí byl samozřejmě i Oscar Wilde, byť v jeho případě v 90. letech 19. století nešlo o politické názory, nýbrž o homosexualitu („gross indecency“). Jeho existenciální autobiografický dopis De Profundis – nebo knižní esej ve formě dopisu – je od vězeňské zkušenosti neodmyslitelný a také ji posouvá do obecnější existenciální roviny.",
  "Vězeňská literatura se často vyznačuje úzkým propojením nebo prolínáním uměleckého a intelektuálního, politického nebo filozofického přístupu, tak je tomu ostatně i u Havlovy skici, která je navzdory specifické estetice pantomimy zároveň i filozofickým esejem o uvězněnosti. Čistě intelektuální dominantu mají poznámky ikonické postavy italské, evropské, světové levice Antonia Gramsciho, které vznikaly ve fašistickém žaláři převážně v Turi na jihu Itálie (v Apulii), později ve vězeňských klinikách v Římě. Quaderni del carcere (Sešity z vězení) jsou souborem politicko-filozofických a kulturně-teoretických poznámek, které už svým názvem vyzdvihují místo vzniku, ačkoliv se týkají širokého okruhu problémů levicového myšlení.",
  "Kult heterogenní literatury psané ve vězení obsahuje pro proces jeho recepce ovšem i něco případně nebezpečného: všichni výše jmenovaní se totiž nakonec proslavili, jejich jmény jsou nazývány školy, letiště, jejich práci a hrdinství připomínají památníky a muzea. Možná bychom je a jejich vězeňskou literaturu, tematicky dalece přesahující fenomén vězení, jinak ani neznali. I v případě Václava Havla jeho skicu nelze oddělit od všeho, co víme – ale tehdy se nevědělo – o pokračování příběhu tohoto mikrodíla: půldruhého měsíce po napsání skici autor opustí vězení a za tři čtvrtě roku se stane celosvětově oslavovaným prezidentem nezávislého Československa.",
  "Z odstupu času to vypadá, jako by tvorba ve stavu uvěznění byla jakousi pikantní dobrodružnou zápletkou na cestě za slávou a do učebnic. Ale nepředpojatý pohled do dějin i přítomnost nás učí, že tomu tak není. Psát ve vězení není nějaká ozdoba životopisu. V naší současnosti a v naší relativní geografické blízkosti dnem i nocí fyzicky a psychicky trpí v ruských a běloruských věznicích - a samozřejmě v desítkách jiných podobných zařízení po celém světě - tisíce politických vězňů, kteří němě volají po naší pozornosti a účasti. Mnozí z nich nemají ponětí, jak skončí, a přesto dokážou najít tu nepravděpodobnou vnitřní sílu, aby ve své extrémní situaci praktikovali tvůrčí činnost univerzálního dosahu, aby zůstali bdělí jen z principu, silou vůle a nadání. Nemusí přitom jít nutně o beletrii. U osobností, jako je Alexej Navalnyj nebo hudební virtuos z Birobidžanu Pavel Kušnir, může být „tvůrčím psaním“ nadčasového významu cokoliv, co se jim podařilo ve vězení napsat a dostat ven. Tím spíš, že politickému vězni může jít taky o život. Vězeňské psaní se vyznačuje dvojí dramatickou otázkou: zda a jak se výsledek dostane za zdi kriminálu – a zda, případně kdy bude na svobodě i jeho autor(ka)? Zrovna oba výše jmenovaní pisatelé věznění v Rusku nepřežili a ve věku 47, respektive 40 let možnost dalšího psaní skončila jejich smrtí – Navalného otrávili jedem, Kušnir pravděpodobně podlehl následkům hladovky.",
  "Možná nejznámější umělkyní, která v polovině 20. let 21. století tvoří jako politická vězenkyně v putinském systému kriminálů a lágrů, je Žeňa Berkovič, režisérka inscenace Finist, jasný sokol o ženách, které se vinou své naivity provdaly za bojovníky Islámského státu a dostaly se do problémů. Hru napsala Svetlana Petrijčuk, premiéra se konala 2020, v roce 2022 získalo představení významnou ruskou divadelní cenu Zolotaja maska (Zlatá maska). V květnu 2023 byly obě autorky zatčeny a v létě 2024 odsouzeny k trestu několikaletého vězení za „ospravedlňování terorismu“ – o skutečném důvodu perzekuce se spekuluje. Ve vazbě Berkovič napsala knihu Chovanci (Pitomcy). Vtipná vězeňská pohádka z uzavřené, blíže neurčené instituce – zvířecího útulku či laboratoře – líčí v tradici orwellovské farmy chovance jako produkt systému, který manipulativně přiměl společnost přijmout logiku věznitele, podřídit se ponižujícím mechanismům kontroly a účelových odměn a soutěžit o přízeň vrchnosti. Groteskní logika zkorumpovaných poměrů generuje i vlastní poetiku: sarkastickou a absurdní. Absurdita tu ale není jen humornou poetikou s dadaistickými kořeny, ale – tak jako tomu kdysi bylo u Havla – uceleným politickým programem.",
  "Havel, tak jako mnozí před ním a mnozí po něm, dokázal ze své situace vytěžit maximum – ale také byl ochotný platit poměrně vysokou cenu, za kterou získal svrchovanou bdělost a jejím prostřednictvím obrovskou míru odstupu a vnitřní svobody – už ve vězení. Žeňa Berkovič, jejíž vězeňské dílo do češtiny přeložila Kateřina Šimová pro nakladatelství Maraton, tyto odvěké, ale vzácné a draze vykoupené dispozice obnovuje v podmínkách pronásledování svobodomyslných umělců nynějšího putinismu.",
  "Bdělost, která umožňuje odstup a hravý humor, označuje typ autorství, ve kterém subjekt nedokáže „vypnout“, vnitřně odpočívat, spokojit se se zavedenou kategorizací jevů nebo rezignovat. Je to subjekt odsouzený k invenčnímu pozorování a vyvozování důsledků, k analytickému svědectví o sobě a svém okolí. Vězeň bdělosti je svědek vlastního osudu a doby, který nemůže „zavřít oči“ – nebo spíš mysl – před skutečností, ať je jakákoliv.",
];

export default function Page() {
  return (
    <ArticlePage
      slug="politicti-vezni"
      tema="Vězení a bdělost"
      autor="Tomáš Glanc"
      image="/1766237746-perpetuum-6.jpg"
      perex="Václav Havel ve své pantomimě, jejíž libreto napsal ve vězení, zaujímá k situaci uvěznění emancipující odstup. Zdůrazňuje vězení jako obecně svízelnou situaci jedince, jak o tom svědčí titul Perpetuum mobile i zmínka o Sisyfovi v režijní poznámce. Nezabývá se svým politicky motivovaným uvězněním, nýbrž spíš obecně lidským přesahem, který zkušenost vězně nabízí. Odstup mimochodem zaujímá nejen k motivům uvěznění, ale i k divadelním prostředkům, kterými přitom disponuje. Ve chvíli, kdy Havel na jaře 1989 na svém díle pracuje, má za sebou už pětadvacet let mezinárodně úspěšné kariéry dramatika. Nicméně v tomto případě divadelní prostředky, v Havlově případě především slovo, jazyk, redukuje de fakto na nulu a pouští se na tenký, pro jeho poetiku netypický led nonverbálního divadla s prvky klauniády. Jako by se nejen na svou situaci vězně, ale i na divadlo, které je základním východiskem jeho uměleckého vyjadřování, podíval zvenčí a z nové perspektivy."
    >
  {ODSTAVCE.map((t, i) => <p key={i}>{t}</p>)}
    </ArticlePage>
  );
}
