import ArticlePage from "@/components/ArticlePage";
import { articleMetadata } from "@/lib/articleMeta";

export const metadata = articleMetadata({
  slug: "roman-zotov-mikshin",
  title: "Pro politické vězně je tělo a mysl nástroj společenské změny",
  description:
    "Před osmnácti lety opustil rodné Rusko, dnes je hlasem politických vězňů v Národním divadle. Rozhovor s Romanem Zotovem-Mikshinem, jediným účinkujícím inscenace Perpetuum Havel.",
  image: "/FOTO4.jpg",
  width: 2000,
  height: 1333,
});

const BLOKY: { q: boolean; t: string }[] = [
  { q: true, t: "Romane, jaká byla premiéra?" },
  { q: false, t: "Mám z ní velmi dobrý pocit. Často si říkám, že by můj výkon mohl být lepší, ale to se opírám o své vnitřní pochody a o porozumění inscenaci zevnitř, které divák samozřejmě nemůže vidět. Když se naopak opřu o včerejší reakce publika a zpětnou vazbu diváků, mám opravdu pocit, že se premiéra povedla. A mám z toho obrovskou radost. Neobešel jsem se ale bez trémy a deset minut před začátkem jsem se přistihl, jak si říkám: „Proč si to dělám? Proč si to znovu dělám?“ (Směje se.)" },
  { q: true, t: "V jaké fázi představení tě tato tréma opouští, pokud vůbec?" },
  { q: false, t: "Během premiéry cítím trému vždycky, někdy i po celý večer. Konkrétně včera ze mě stres opadl až v momentě, kdy jsme o půlnoci tančili salsu v jednom z avignonských klubů. To jsem si konečně vydechl." },
  { q: true, t: "Čím se Perpetuum Havel liší od tvých ostatních projektů?" },
  { q: false, t: "Je to moje první celovečerní sólo. Sice buduji vztah s různými objekty na jevišti, ale stále jsem zde jedinou živou bytostí. Dále jsem taky nikdy neviděl inscenaci fyzického divadla, která diváka zavádí do prostředí vězení nebo cely. Až na jedno studentské a jedno zahraniční zpracování Perpetuum mobile nikdo nikdy neinscenoval, a tak jsem neměl žádný výraznější opěrný bod v dosavadních adaptacích. Jedná se také o první práci, která mě přivedla ke čtení Havlových dramat a esejů. Například nesmírně moc souzním s Mocí bezmocných. Nyní, při čtení jeho dalších děl, si uvědomuji, kolik z jeho tvorby jsme do naší inscenace dostali. Jsem velice rád, že mě tato práce k jeho textům přivedla. Každému, kdo ještě nic od Havla nečetl, nebo sice četl, ale obsah už zapomněl, jej vřele doporučuji. I když to zní od Rusa směrem k Čechům trochu zvláštně. (Směje se.)" },
  { q: true, t: "Vzpomeneš si na to, kdy jsi Perpetuum mobile četl poprvé?" },
  { q: false, t: "Ano. Vlastně mi ten text nejprve předčítal režisér Petr Boháč, což byl sám o sobě velmi zajímavý zážitek. Nikdy předtím jsem ho neslyšel číst nahlas a bylo fascinující sledovat, jak se při tom úplně proměnil. Důsledkem mého zaujetí ale bylo, že jsem se přestal soustředit na obsah. (Směje se.) Až při dalším čtení ve mně text začal skutečně rezonovat. To, co si ale pamatuji už z toho prvního setkání, byl samotný princip onoho perpetuum mobile – nekonečného koloběhu, opakování a absurdní komiky. Už samotný Havlův způsob psaní je velmi specifický. Tím, že musel libreto kvůli omezenému rozsahu vězeňských dopisů přepsat do druhé, výrazně zkrácené verze, je text vystavěný z velmi krátkých vět a velkých zkratek. Má to zvláštní efekt – jako by na jednu stranu představivost byla omezena, ale zároveň i podněcována. Ostatně sám Havel v závěru vybízí inscenátory ke svobodnému pojetí slovy: „Fantazii se meze nekladou.“" },
  { q: true, t: "Inscenace je nonverbální. Jak jste s Petrem Boháčem hledali fyzický jazyk postavy politického vězně?" },
  { q: false, t: "Petr už na začátku přišel s velmi jasným principem – s neustálým jemným pohupováním těla. Od něj se pak odvíjely všechny naše improvizace. Pracovali jsme s minimalistickou hudbou, která ten pohyb prohlubovala a postupně rozvíjela. Dávala čas zůstat v určitém stavu, ale zároveň i jemnou změnou tónu naznačovala možnost změny pohybu. Díky tomu jsem se dostával do velmi křehkých, až hraničních stavů vědomí, někam mezi bdělost a trans. Otevírala se ve mně místa, ke kterým se člověk běžně nedostane – vlastní traumata nebo něco velmi intimního a zranitelného. Improvizace někdy trvaly půl hodiny, jindy hodinu, a po jejich skončení jsem často nebyl schopný mluvit. Jen jsem chodil a tekly mi slzy. Zároveň jsem ale cítil, že jsem beze slov vyjádřil něco velmi osobního a důležitého. Pak jsme se začali opírat přímo o Havlovu hru. Vězeň A má přesně strukturovaný den, který se neustále opakuje a je tvořený sérií každodenních úkonů. Společně jsme hledali, jaké činnosti tvoří život mé postavy. Některé vycházejí přímo z libreta, jiné jsme doplnili na základě toho, co dnes víme o životě politických vězňů. Bylo pro nás důležité nevyprávět jen příběh z minulosti. Chtěli jsme zdůraznit, že politické věznění není historická kapitola – děje se i dnes. A bohužel nic nenasvědčuje tomu, že by se nemělo dít i zítra." },
  { q: true, t: "Pro podtrhnutí aktuálnosti tématu jste během příprav studovali osudy současných politických vězňů. Co je podle tebe, bez ohledu na zemi nebo podobu režimu, spojuje?" },
  { q: false, t: "Síla ducha. Tu jsem našel u všech, se kterými jsme se buď setkali osobně, nebo jejichž příběhy jsem poznával prostřednictvím deníků Alexeje Navalného či výpovědí dalších lidí před soudem. Ať už svůj rozsudek znají, nebo na něj teprve čekají, mluví s neuvěřitelnou vnitřní silou, jako by v tu chvíli neexistovalo nic jiného než jejich přesvědčení a pravda, kterou hájí. Právě v tom vidím jejich společný jmenovatel. Díky tomu jsem si – a to se mi nestává často – téměř jistý, že jsme při tvorbě inscenace narazili na samotné jádro. Proto si myslím, že si můžeme dovolit mluvit o politických vězních bez ohledu na to, z jaké země pocházejí. A možná i obecně o lidech, kteří vědí, že byli neprávem odsouzeni. Označení politický vězeň popisuje jen určitý typ perzekuce, ale existuje mnoho lidí, kteří jsou za mřížemi nespravedlivě a nesou si stejné utrpení. Když se ještě vrátím k té síle ducha, ona je nezlomná. Je skrytá, ale zároveň všeprostupující. Jak píše Havel v Moci bezmocných, přežívá pod nánosem života ve lži – latentně přítomná, obtížně rozpoznatelná, ale nikdy nemizící. Každý autoritářský systém se ji proto snaží potlačit ve chvíli, kdy ji rozpozná." },
  { q: true, t: "Když se teď na dané podíváme z jiného úhlu a přesuneme se k tématu svobody, myslíš, že je možné ji člověku beze zbytku vzít?" },
  { q: false, t: "Myslím, že ano – pokud člověk o sílu ducha přijde. Když se poddá, nejdřív zpravidla selže tělo a potom mysl. Někdy se to děje současně. Ale právě příběhy lidí, se kterými jsme se setkávali, ukazují i opačnou zkušenost. Vzpomínám si třeba na Palinu Šarendu-Panasjuk (někdejší politickou vězenkyni v Bělorusku, aktuálně žijící v polském exilu, pozn. red.). Říkala, že dokud v sobě měla sílu ducha, její tělo dokázalo snášet násilí, o kterém si dřív vůbec neuměla představit, že by ho přežila. Jako by se mu dokázalo přizpůsobit. To pro mě bylo nesmírně silné. Zároveň u ní zazněla ještě jedna věc, se kterou jsem se u ostatních setkával jen výjimečně – mluvila o nenávisti. Ne jako o něčem, co ji ničí, ale jako o energii namířené proti těm, kteří ji do vězení dostali. Obecně máme tendenci nenávist chápat jako něco, čemu bychom se měli vyhýbat. V jejím případě ale právě tenhle silný odpor paradoxně posiloval její odhodlání a sílu ducha." },
  { q: true, t: "Jak bys onu sílu ducha definoval?" },
  { q: false, t: "Je to vědomí, že stojíš na straně pravdy. Ne pravdy ve smyslu, že já mám pravdu, ale pravdy jako něčeho, co člověka přesahuje – v existenciální rovině. Samozřejmě víš, co se stalo, víš, že jsi nic neudělala a že jsi ve vězení neprávem. Ale právě ten nesouhlas s bezprávím pomáhá probudit sílu ducha, která je v nás za běžných okolností spíš skrytá. Pro mě je to vlastně život sám. Je to okamžik, kdy člověk překročí sám sebe. Ostatně většina politických vězňů, když mluví veřejně, nemluví o sobě. Mluví o tom, že jejich země má být svobodná, že jejich národ má mít stejná práva jako ostatní, že lidé mají žít důstojně. Nevedou boj jen za sebe. Své tělo i svou mysl používají jako nástroj k tomu, aby se mohla odehrát změna, která je větší než oni sami. V tom je pro mě síla ducha. Je to život, který se brání tomu, co je nepřirozené. Když se v těle objeví nemoc, organismus se ji snaží překonat. A podobně i člověk – překračuje vlastní tělo i mysl, aby mohl působit ve prospěch něčeho, co považuje za správné." },
  { q: true, t: "V rámci příprav inscenace jste byli v úzkém kontaktu s někdejšími běloruskými vězeňkyněmi, především zmíněnou Palinou Šarendou-Panasjuk, která nyní žije v polském exilu. Co pro vás během zkoušení Palina představovala?" },
  { q: false, t: "Měli jsme s ní dvě velká setkání a několik menších, spíše zaměřených na reflexi a sdílení. Její role v průběhu příprav byla nezastupitelná, protože Palina je výjimečná v tom, že už dokáže mít určitý odstup od vlastní bolesti. Je schopná to, čím prošla, nejen popsat, ale také převést do obrazů – a to je pro divadlo nesmírně cenné. Říkala nám, že si během věznění i po propuštění některé události uchovávala právě skrze obrazy. Ale jelikož sama není výtvarnice, popisovala tyto své vzpomínky v obrazech umělé inteligenci, která jí pomáhala vizualizace vytvářet. A právě prostřednictvím těchto vizualizací nám předávala nejen konkrétní situace, ale především jejich atmosféru a vnitřní význam. Myslím, že právě množství zdánlivě drobných a bezvýznamných detailů vytváří výslednou pravdivost. Nejde o dokumentární divadlo, ale ta esence jejích slov a zkušeností je v inscenaci přítomná. Hledali jsme podobnou podstatu – a její obrazy nám v tom velmi pomohly. Bylo to pro nás velmi křehké a silné setkání. Když jsme během jedné ze zkoušek pro Palinu a další čtyři bývalé vězeňkyně – Irinu, Marii, Janu a Olgu – hráli, objevil jsem v sobě pocit, který jsem nikdy nezažil, bylo to nesmírně náročné. Zároveň to ale bylo pro finální podobu inscenace velice obohacující. Dostali jsme od nich obrovskou podporu, kterou jsme vůbec nečekali. Řekly nám: „Děkujeme za to, že ztvárňujete to, co jsme prožívaly my.“ A to i přesto, že to nepřenášíme dokumentárně, ale prostřednictvím divadelní inscenace." },
  { q: true, t: "Je něco, co tě během těch setkání s bývalými vězeňkyněmi Lukašenkova režimu překvapilo?" },
  { q: false, t: "Ano, když Palina poprvé viděla část naší práce, říkala, že to vězení vypadá skoro jako hotel. Byli jsme tehdy ještě v první fázi zkoušení a teprve jsme hledali podobu některých situací. Její reakce nám ale ukázala, že to, co jsme si představovali jako velmi tvrdé, bylo pořád ještě daleko od reality, kterou ona zažila – zejména během sedmi měsíců na samotce, v nejhorším období. Tehdy jsme si uvědomili, že i když Havel ve svém textu samozřejmě nijak nezmenšuje utrpení politického vězně, existují místa na světě, kde může být vězeňské peklo ještě mnohem intenzivnější. A zároveň si myslím, že ani Bělorusko není poslední hranicí lidského zla. Palina říkala, že lidské zlo nemá meze – stejně jako lidské dobro. Vynalézavost zla je bohužel nekonečná. Vyprávěla nám například o tom, jakým způsobem ji ve vězení ponižovali a týrali i skrze zdánlivé maličkosti. Když ji v zimě pouštěli na procházku, dostala papírové boty. Dostávala oblečení s chybějícími knoflíky nebo s knoflíky našitými tak, aby jí co nejvíce znepříjemňovaly život. Byly to drobnosti, ale opakovaly se neustále – na každém kroku využívali jakoukoli možnost, jak ji ponížit nebo jí způsobit další utrpení. A přitom měla jen velmi málo příležitostí, kdy mohla svůj nesouhlas otevřeně projevit." },
  { q: true, t: "Zmíněné papírové boty mohou v inscenaci vypadat jako divadelní stylizace, ale mají oporu v realitě. Jaké další autentické zkušenosti politických vězňů a vězeňkyň se v Perpetuum Havel odrážejí?" },
  { q: false, t: "Například blikající světlo, kterým byly vězeňkyně systematicky týrány. V noci se nevypínalo, způsobovalo jim silné migrény a znemožňovalo jim několik dní spát. Nebo takzvané „krmítko“ – malý otvor ve dveřích cely, kterým dostávaly jídlo. Aby si převzaly tác nebo talíř, musely si k němu kleknout. V té poloze viděly jen část těla člověka na druhé straně dveří, často pouze jeho poklopec. A právě v této pozici je každý den nutili opakovat své jméno, příjmení a důvod, proč jsou ve vězení. Musely to odříkávat v kleče, bez vysvětlení nebo signálu, že mají začít. Právě takové zdánlivě malé detaily ukazují, jak systematicky lze člověka zbavovat důstojnosti." },
  { q: true, t: "Bachař se v Perpetuum Havel také objevuje. Je součástí projekce a jeho obličej je cenzurovaný." },
  { q: false, t: "Ano, protože vězeň často vůbec neví, s kým jedná. Neví, kdo ten člověk je, jaké má úmysly, co se bude dít. Nejde o konkrétního člověka, ale o princip moci a nejistoty, ve které vězeň žije. Palina nám vyprávěla, že i samotné cinkání klíčů v nich vyvolávalo okamžitou nervozitu. Stačilo, aby se ozval ten zvuk, a všechny ženy zpozorněly. Mohlo přijít cokoli. Je zvláštní, že stejný zvuk v běžném životě vnímáme úplně jinak. Čekáme doma někoho blízkého, slyšíme klíče v zámku a máme radost, že někdo přichází. Ve vězení se z toho samého zvuku stává předzvěst strachu." },
  { q: true, t: "V inscenaci se objevuje také velmi konkrétní tělesný obraz – tvoje postava stojí čelem ke zdi s rukama nad hlavou a prázdnými dlaněmi otočenými ven. Vychází i tento moment z autentických zkušeností vězňů a vězeňkyň?" },
  { q: false, t: "Ano. Je to obraz spojený s prohlídkami, které jsou běžnou součástí vězeňské reality. A i v těchto situacích se odehrávalo skryté násilí – často v podobě ponižování a překračování osobních hranic, s prvky sexualizovaného násilí. Tohle se tam také bohužel děje naprosto běžně." },
  { q: true, t: "Ty jsi původem Rus, v Čechách žiješ osmnáct let, polovinu svého života. V jakém věku mladý člověk už pomalu začíná vnímat, že žije ve státě, který využívá politickou perzekuci jako jeden z mocenských nástrojů?" },
  { q: false, t: "Myslím, že na to neexistuje jednoznačná odpověď. Záleží na tom, kde člověk žije, v jakém prostředí vyrůstá a s kým se stýká. Já jsem se narodil v Tule, asi 180 kilometrů od Moskvy. Na ruské poměry je to spíš malé, provinční město, i když se odtud samozřejmě často jezdí do Moskvy – většinou ale s určitou fascinací a obdivem k hlavnímu městu. Než jsem v téměř osmnácti odjel do Česka, jsem se nad tím vlastně vůbec nezamýšlel. Byl jsem přesvědčený, že Rusko je nejlepší země na světě. Až zpětně si člověk uvědomí ten paradox: pokud jsem tomu opravdu věřil, proč jsem vlastně odjel do jiné země? Je v tom určitý rozpor, možná i forma společenské schizofrenie, kterou podle mě mnoho lidí v Rusku nějakým způsobem zažívá. Zároveň ale znám lidi, kteří už v šestnácti letech začali cítit, že něco není v pořádku. Že něco nesedí. Začali přemýšlet o tom, co mohou změnit, jak mohou ovlivnit prostředí, ve kterém žijí, nebo jestli z něj odejít. To nebyl můj případ. Já jsem se rozhodoval spíš intuitivně. Myslím, že jsem tu intuici částečně zdědil po mámě – oba jsme nějak cítili, že odjet do Česka by mohl být dobrý krok, i když jsem o této zemi tehdy skoro nic nevěděl. Věděl jsem jen, jak vypadá Pražský hrad, a to vlastně z jednoho jediného obrázku. A najednou jsem se rozhodl, že Česko je dobrá země pro život. Takže Pražský hrad opravdu funguje. (Směje se.)" },
  { q: true, t: "Sám říkáš, že obraz Ruska jako nejlepší země na světě je v tamní společnosti rozšířený. Může i to být jedním z důvodů, proč je pro mnoho lidí těžké si připustit, že něco není v pořádku, natož uvažovat o emigraci?" },
  { q: false, t: "Ano. Já, moje žena i mnoho dalších lidí, se kterými se o tom bavíme, jsme byli dlouho přesvědčení, že nic lepšího neexistuje. Rusko má obrovské množství kulturních obrazů – písní, příběhů a různých projevů – které vytvářejí pocit, že právě tam je člověk doma a že právě tam je něco výjimečného. Člověk se vrátí zpátky a najednou cítí, že tam jeho srdce tluče jinak. Něco se ho hluboce dotkne. A právě to je velmi silné, protože si pak neuvědomuje, že už je součástí určitého způsobu myšlení. Postupně do toho člověk vrůstá. Vychovávají ho k určitému obrazu světa a on dlouho ani nevidí, že ten obraz není úplný. Pak je velmi těžké začít pochybovat, protože nezpochybňujete jen politický systém – zpochybňujete něco, co je součástí vaší identity. A právě proto může být těžké odejít. Nejde jen o to opustit zemi, ale opustit právě tu představu, že je to nejlepší místo na světě." },
  { q: true, t: "Pokud se nepletu, ty už se v aktuální politické situaci do Ruska vrátit nemůžeš." },
  { q: false, t: "Můžu, ale už bych tam musel zůstat. Je tam víc než devadesátiprocentní šance, že bych se zpátky nevrátil – že by mě povolali a možná bych zemřel na vojně nebo ve válce. I když jsem odhlášený, mám trvalý pobyt v Česku a podle zákona bych k odvodu neměl jít, stejně u mě během jedné z návštěv Ruska byl nějaký pán s lístkem, že mě chtějí povolat. Což vlastně nedává smysl, protože podle zákona na to nemají právo. Ale stejně za mnou přišli." },
  { q: true, t: "A když Rusko pozoruješ z dálky – jak se za těch osmnáct let proměnilo?" },
  { q: false, t: "Já jsem tam nebyl už pět let, což je strašně dlouhá doba. Dřív jsme tam byli zvyklí jezdit každý rok nebo dva a já vlastně vůbec nedokážu říct, jaké to tam dnes je. Poslouchám a sleduji hlavně opoziční média, která samozřejmě vytvářejí obraz zaměřený na to, co je špatně. Takže určitě ve mně vytvářejí možná o něco temnější obraz, než jaká je realita. Podle toho, co vím, je to země, ve které bych se dnes bál projevit. Musel bych přemýšlet, co a komu říkám. Nemohl bych poslouchat skoro nic z toho, co dnes poslouchám, nemohl bych otevřeně říct, co čtu, protože za to bych mohl jít sedět. Najednou mám pocit, jako kdybychom mluvili o Severní Koreji, a přitom je to Rusko. A to je pro mě strašně zvláštní, protože já Rusko pořád miluji – tu zemi, její potenciál, její možné štěstí, její možnou svobodu. Často se lidem, jako jsem já, nebo lidem, kteří jsou ještě aktivnější, říká, že nejsme patrioti. Já si ale myslím, že jsme možná právě ti patrioti, protože nás bolí srdce." },
  { q: false, t: "Vždycky, když jsem jel do Ruska, měl jsem pocit: „Konečně.“ Jako kdyby mě někdo pustil z nějaké nesvobody – i když to samozřejmě není pravda. Ale byl jsem tam ve svém jazyce, mezi místy, která znám od dětství, a najednou jsem se napojil na všechno. Jako kdyby ze mě vyšly dráty a já se napojil na celý prostor, na všechny lidi, na puls té země, té kultury, toho místa. A teď se bojím, že kdybych tam musel jet, tak bych ty dráty musel úplně schovat. Několika vrstvami něčeho, co by mě chránilo. Jen bych pozoroval, jak se všechno proměnilo. A to je pro mě obrovská změna. Protože dřív pro mě cesta do Ruska vždycky znamenala radost. Dnes mám s tou představou spojený strach." },
  { q: true, t: "Protože jsi tam nebyl už pět let, předpokládám, že ten zlom určila válka. Šokovalo tě, že k invazi došlo?" },
  { q: false, t: "Já jsem tomu vůbec nevěřil. Myslel jsem, že to skončí hrozně rychle, že to musí být nějaký omyl. V té době jsem nebyl tolik uvědomělý v oblasti politiky a geopolitiky, nesledoval jsem tolik, jak se věci vyvíjejí a kam směřují, takže jsem si vůbec nedokázal představit, že se to opravdu stane. Máme příbuzné z Ukrajiny, a když za námi přijeli a začali u nás žít, teprve tehdy jsem si naplno uvědomil tu hrůzu, která se děje. To, za jakých podmínek museli utíkat a co všechno tomu předcházelo. Ono se to nestane najednou – všechno se postupně nabaluje a člověk si na určité věci dokáže zvykat. Ale šok je přesné slovo. Najednou nevíš, jak máš jednat. Samozřejmě víš, že se musíš postarat o sebe, o své nejbližší, ujistit se, že jsou v pořádku. Ale pak přichází otázka: co s tím dělat ve větším měřítku? Zároveň to v něčem přineslo i určité vystřízlivění z představy, že stát za člověka všechno vyřeší a postará se o něj. Najednou si uvědomíš: nemůžu se opřít o stát nebo nějaké instituce, musím začít jednat sám – s pomocí rodiny, blízkých lidí a komunity. Ta schopnost jednat, ta vůle něco dělat, najednou zesílí. Protože už nechceš jen čekat a věřit, že to za tebe někdo vyřeší." },
  { q: true, t: "Dnes jsi hlasem politických vězňů v divadelní inscenaci Národního divadla. S čím by sis ideálně přál, aby diváci po zhlédnutí představení odcházeli?" },
  { q: false, t: "Přál bych si, aby si uvědomili, že to, co vidí, není jen divadelní zpracování, ale odkazuje to ke skutečné hrůze, která se děla, děje a s největší pravděpodobností se ještě nějaký čas dít bude. Aby si uvědomili, že s tím něco můžeme dělat. Že podpora může začínat i u symbolických gest, která nejsou tak bolestivá nebo nekomfortní, ale že existuje možnost nějakým způsobem se postavit na stranu těch, kteří pomoc potřebují. A když to vezmu ještě šířeji, přál bych si, aby se člověk skrze ten zážitek dostal sám k sobě. Nechci znít arogantně, ale možná bych si přál, aby si člověk připustil, že ne celý život žije úplně v pravdě. Protože síla lži je obrovská. Je velmi svůdná, barevná a často i pohodlná. Ale zároveň člověk někde hluboko ví, kam vede cesta, která je pravdivá. Připomíná mi to první verš Jóga súter: „A teď jóga.“ Ne ve smyslu cvičení, jak se to dnes často chápe, ale ve smyslu propojení člověka se sebou samým a s celkem života. Jako kdyby to znamenalo: prošel jsi různými zkušenostmi, zkusil jsi mnoho věcí – a teď se zkus opravdu podívat. Takže bych si přál, aby naše inscenace byla pro diváky dalším střípkem v hledání života v pravdě." },
];

export default function Page() {
  return (
    <ArticlePage
      slug="roman-zotov-mikshin"
      tema="Pro politické vězně je tělo a mysl nástroj společenské změny"
      autor="Martina Sedláková"
      image="/FOTO4.jpg"
      perex="Před osmnácti lety opustil rodné Rusko, dnes je hlasem politických vězňů v Národním divadle. Roman Zotov-Mikshin je jediným účinkujícím inscenace Perpetuum Havel, která měla světovou premiéru 4. července v rámci Off programu divadelního festivalu v Avignonu. S performerem, jehož výkon si vysloužil chválu francouzských kritiků v bezmála desítce recenzí, jsme si povídali den po premiéře přímo v centru festivalového dění."
    >
      {BLOKY.map((b, i) =>
        b.q ? (
          <p key={i} className="font-semibold text-white pt-3">{b.t}</p>
        ) : (
          <p key={i}>{b.t}</p>
        )
      )}
    </ArticlePage>
  );
}
